name: White Paper
markdown: redcarpet
highlighter: true
url: http://kyne0116.github.io/
gems: [jekyll-paginate,  jekyll-gist]
paginate: 8
logo:             logo.png
disqus_shortname:
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           Kyne0116
  avatar:         <avatar-image-link>
  email:          kyne.li@hotmail.com
  # Social networking links used in footer. Update and remove as you like.
  github:   https://github.com/kyne0116
